#!/usr/bin/env python3
import sys, os, math, argparse, datetime
import cairo
import numpy as np
# from IPython.display import SVG, display, Image

# Some constants
PROG = sys.argv[0].split('/')[-1]
MIN_CHR_LEN = 1_000_000
SCALE = 1_000_000
STEP = 5_000_000
IMG_WIDTH = 500
IMG_HEIGHT = 500
FONT_SIZE = 10
MAX_LOG2 = 3
SCALE_QUANTILE = 99
SCALE_ROUND = 0.5

#
# Command line options
#
def parse_scale_limit(value, name):
    '''
    Parse a limit of the color scale, either 'auto' or a number. Min
    limits must be negative and max limits positive.
    '''
    assert name in ['Min', 'Max']
    if value.lower() == 'auto':
        return 'auto'
    try:
        value = float(value)
    except ValueError:
        sys.exit(f'Error: {name} log2 value of the color scale ({value}) must be a number or \'auto\'.')
    if name == 'Max' and not value > 0:
        sys.exit(f'Error: Max log2 value of the color scale ({value}) must be > 0.')
    if name == 'Min' and not value < 0:
        sys.exit(f'Error: Min log2 value of the color scale ({value}) must be < 0.')
    return value

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('-f', '--fai', required=True,
                   help='(str) Path to genome index in FAI format.')
    p.add_argument('-t', '--in-table', required=True, 
                   help='(str) Path to input table of window statistics, generated by `bin_genome_stats.py`.')
    # Optional Parameters
    p.add_argument('-c', '--chroms', required=False, default=None,
                   help='(str) Path to chromosome order list [default=None].')
    p.add_argument('-o', '--out-dir', required=False, default='.', 
                   help='(str) Path to output directory [default=.].')
    p.add_argument('-n', '--basename', required=False, default=None,
                   help='(str) Basename of output files [default=In table basename].')
    p.add_argument('--title', required=False, default=None,
                   help='(str) Title of the plots, followed by the type of plot [default=Basename].')
    p.add_argument('-m', '--min-len', required=False, default=MIN_CHR_LEN,
                   type=float, help=f'(int/float) Minimum chromosome size in bp [default {MIN_CHR_LEN:,}]')
    p.add_argument('-s', '--scale', required=False, default=SCALE, type=float,
                   help=f'(int/float) Scale chromosome lengths to this value [default={SCALE:,}],')
    p.add_argument('-p', '--step', required=False, default=STEP, type=float,
                   help=f'(int/float) Steps for size for axis tick marks [default={STEP:,}].')
    p.add_argument('--img-height', required=False, default=IMG_HEIGHT, type=int,
                   help=f'(int) Image height in pixels [default={IMG_HEIGHT}].')
    p.add_argument('--img-width', required=False, default=IMG_WIDTH, type=int,
                   help=f'(int) Image width in pixels [default={IMG_WIDTH}].')
    p.add_argument('--img-format', required=False, default='pdf',
                   help='(str) Image output format [default=pdf]')
    p.add_argument('--max-log2', required=False, default=str(MAX_LOG2),
                   help=f'(int/float/\'auto\') Upper limit of the log2 enrichment color scale; values above this are clamped. If \'auto\', set the limit for each plot from the data (see --scale-quantile) [default={MAX_LOG2}].')
    p.add_argument('--min-log2', required=False, default=None,
                   help='(int/float/\'auto\') Lower limit of the log2 enrichment color scale (a negative value); values below this are clamped. If \'auto\', set the limit for each plot from the data (see --scale-quantile). If not set, the scale is symmetric, i.e., -1 * --max-log2 [default=None].')
    p.add_argument('--palette', required=False, default=PALETTE, choices=list(PALETTES),
                   help=f'(str) Diverging color palette for the heatmaps, from depleted to enriched values. ColorBrewer palettes are oriented so that the first color in the name marks enriched values (e.g., red in RdYlGn) [default={PALETTE}].')
    p.add_argument('--reverse-palette', required=False, action='store_true',
                   help='(flag) Reverse the order of the color palette.')
    p.add_argument('--scale-quantile', required=False, default=SCALE_QUANTILE, type=float,
                   help=f'(int/float) When --max-log2 is \'auto\', percentile of the absolute log2 values used as the limit of the color scale, rounded up to the nearest {SCALE_ROUND} [default={SCALE_QUANTILE}].')
    # Check inputs
    args = p.parse_args()
    assert args.scale <= args.min_len
    if args.chroms is not None:
        assert os.path.exists(args.chroms)
    assert os.path.exists(args.fai)
    assert os.path.exists(args.in_table)
    assert os.path.exists(args.out_dir)
    assert args.img_format in ['pdf', 'svg']
    # The limits of the scale are either 'auto' or a number
    args.max_log2 = parse_scale_limit(args.max_log2, 'Max')
    if args.min_log2 is not None:
        args.min_log2 = parse_scale_limit(args.min_log2, 'Min')
    if not 0 < args.scale_quantile <= 100:
        sys.exit(f'Error: Scale quantile ({args.scale_quantile}) must be > 0 and <= 100.')
    args.out_dir = args.out_dir.rstrip('/')
    # Adjust the basename if missing
    if args.basename is None:
        args.basename = os.path.basename(args.in_table).removesuffix('.binned_genome_stats.tsv')
    # Standarize the sizes to integers
    args.scale = int(args.scale)
    args.step = int(args.step)
    args.min_len = int(args.min_len)
    return args

# Load the chromosome order list
def read_chromosomes(chrom_f):
    os.path.exists(chrom_f)
    chrom_order = list()
    for line in open(chrom_f, 'r'):
        if line.startswith('#'):
            continue
        chrom = line.strip('\n').split('\t')
        assert len(chrom) == 1
        chrom_order.append(chrom[0])
    print(f'    Read {len(chrom_order):,} records from chromosome order list.', flush=True)
    return chrom_order

#
# Load Fasta index
#

## Chromosome class
class Chromosome:
    def __init__(self, name, length):
        assert type(length) is int
        self.name = name
        self.len  = length
    def __str__(self):
        return f'{self.name} {self.len}'

def load_fai(fai_f, min_len=MIN_CHR_LEN):
    assert os.path.exists(fai_f)
    ## Loop over FAI and extract
    chromosomes = dict()
    n = 0
    assert os.path.exists(fai_f), f'Error: {fai_f} not found.'
    for line in open(fai_f, 'r'):
        if line.startswith('#'):
            continue
        n += 1
        fields = line.strip('\n').split('\t')
        name = fields[0]
        length = int(fields[1])
        if length < min_len:
            continue
        chrom = Chromosome(name, length)
        chromosomes[name] = chrom
    # Report FAI
    print(f'\nRead {n:,} records from the FAI file.\n    Kept {len(chromosomes):,} entries with lengths larger than {min_len:,}', flush=True)
    return chromosomes


def process_chromosome_info(fai_f, chrom_order_f, min_len=MIN_CHR_LEN):
    '''
    Process all chromosome info including FAI and order file.
    '''
    # First, load the FASTA index
    fai = load_fai(fai_f, min_len)
    # If there is no chromosome order provided, use the FAI
    chrom_order = None
    if chrom_order_f is None:
        chrom_order = fai.keys()
    else:
        # Otherwise, read the chromosome order
        chrom_order = read_chromosomes(chrom_order_f)
    # Filter the FAI to just keep those entries
    fai_bak = fai
    fai = dict()
    for chrom in chrom_order:
        chromosome = fai_bak.get(chrom, None)
        if chromosome is None:
            sys.exit(f"Error: {chrom} not found in FAI entries larger than {min_len:,}.")
        assert isinstance(chromosome, Chromosome)
        fai[chrom] = chromosome
    # Report to log
    print(f'    Kept {len(fai):,} chromosome objects after filtering.', flush=True)
    return fai, chrom_order


#
# Load the window proportions file
#

## Window statistic class
class WindowStat:
    def __init__(self, chromosome, start, end, mid,
                 n_elements=0.0, proportion=0.0):
        assert type(start) in [int, float]
        assert type(end) in [int, float]
        assert type(mid) in [int, float]
        assert type(n_elements) is float
        assert type(proportion) is float
        self.chr = chromosome
        self.start = start
        self.end = end
        self.mid = mid
        self.n_elements = n_elements
        self.proportion = proportion
    def __str__(self):
        return f'{self.chr} {self.start} {self.end} {self.mid} {self.n_elements} {self.proportion}'


def load_window_stats_file(win_f, chromosomes):
    '''
    Parse the input window stats file, generated by the 
    `bin_genome_stats.py` script.
    '''
    assert os.path.exists(win_f)
    assert type(chromosomes) is dict
    assert isinstance(list(chromosomes.values())[0], Chromosome)

    ## Initialize the output dictionary based on the read chromosomes
    print(f'\nReading the input windows file:\n    {win_f}', flush=True)
    wins_dict = { chrom : [] for chrom in chromosomes }
    records = 0
    kept = 0

    # The columns for the input file are:
    #    0: Chrom
    #    1: StartBP
    #    2: EndBP
    #    3: MidBP
    #    4: ElementsN
    #    5: ElementsAdj
    #    6: PropSites
    #    7: PropSitesAdj
    # The adjusted values are found by name in the header, since they are
    # the ones plotted.
    cols = None

    # Parse the input windows file
    with open(win_f) as fh:
        for line in fh:
            if line.startswith('#'):
                header = line.lstrip('#').strip('\n').split('\t')
                if 'ElementsAdj' in header and 'PropSitesAdj' in header:
                    cols = { col : i for i, col in enumerate(header) }
                continue
            if cols is None:
                sys.exit('Error: input windows table must have a header with the `ElementsAdj` and `PropSitesAdj` columns.')
            records += 1
            fields = line.strip('\n').split('\t')
            chrom = fields[0]
            if chrom not in wins_dict:
                continue
            start = float(fields[1])
            end = float(fields[2])
            mid = float(fields[3])
            n_elements = float(fields[cols['ElementsAdj']])
            proportion = float(fields[cols['PropSitesAdj']])
            # Make the class for the window
            window_stat = WindowStat(chrom, start, end, mid, n_elements, proportion)
            wins_dict[chrom].append(window_stat)
            kept += 1
    # Report to logs
    print(f'    Read {records:,} records from the input windows table.\n    Retained {kept:,} records.', flush=True)
    return wins_dict

#
# Colors for the chromosome elements
# This includes chromosome lines, tick marks, and labels
class ChromColors:
    def __init__(self, item):
        cols_chrom = {
            'ticks'  : [192.0/255.0, 192.0/255.0, 192.0/255.0],
            'fill'   : [127.0/255.0, 127.0/255.0, 127.0/255.0],
            'line'   : [125.0/255.0, 125.0/255.0, 125.0/255.0],
            'text'   : [ 25.0/255.0,  25.0/255.0,  25.0/255.0],
            'border' : [ 50.0/255.0,  50.0/255.0,  50.0/255.0]
        }
        color  = cols_chrom[item]
        self.r = color[0]
        self.g = color[1]
        self.b = color[2]
        self.a = 1
    def __str__(self):
        return f'R: {self.r:.2f}, G: {self.g:.2f}, B: {self.b:.2f}, A: {self.a:.2f}'


# Color palettes for the heatmaps
# check https://www.colorhexa.com/
#
# Each palette is a list of hex colors, ordered from the lowest (depleted)
# to the highest (enriched) values. The middle color corresponds to a log2
# enrichment of 0 (the genome-wide average), so palettes have an odd number
# of colors. Colors are linearly interpolated between consecutive stops.
PALETTES = {
    # Original palettes
    'RedYellowBlue' : ['#0050f2', '#fcf75e', '#ff0000'], # Blue, Yellow, Red
    'BlueWhiteRed'  : ['#0050f2', '#ffffff', '#ff0000'], # Blue, White, Red
    'ViridisClassic': ['#191970', '#00693e', '#ffa812'], # Indigo, Green, Yellow
    'Mango'         : ['#00693e', '#ffa812', '#b22222'], # Green, Yellow, Red
    'MangoLight'    : ['#449d48', '#f6db6a', '#e54449'], # Green, Yellow, Red
    'MagmaClassic'  : ['#00008b', '#ff2800', '#fcf75e'], # Indigo, Red, Yellow
    # ColorBrewer diverging palettes (11 classes; https://colorbrewer2.org).
    # Reversed from the ColorBrewer order, so that the first color in the name
    # (e.g., Red in RdYlGn) corresponds to the enriched values.
    'RdYlGn'   : ['#006837', '#1a9850', '#66bd63', '#a6d96a', '#d9ef8b', '#ffffbf',
                  '#fee08b', '#fdae61', '#f46d43', '#d73027', '#a50026'],
    'RdYlBu'   : ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
                  '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026'],
    'RdBu'     : ['#053061', '#2166ac', '#4393c3', '#92c5de', '#d1e5f0', '#f7f7f7',
                  '#fddbc7', '#f4a582', '#d6604d', '#b2182b', '#67001f'],
    'RdGy'     : ['#1a1a1a', '#4d4d4d', '#878787', '#bababa', '#e0e0e0', '#ffffff',
                  '#fddbc7', '#f4a582', '#d6604d', '#b2182b', '#67001f'],
    'PuOr'     : ['#2d004b', '#542788', '#8073ac', '#b2abd2', '#d8daeb', '#f7f7f7',
                  '#fee0b6', '#fdb863', '#e08214', '#b35806', '#7f3b08'],
    'BrBG'     : ['#003c30', '#01665e', '#35978f', '#80cdc1', '#c7eae5', '#f5f5f5',
                  '#f6e8c3', '#dfc27d', '#bf812d', '#8c510a', '#543005'],
    'PiYG'     : ['#276419', '#4d9221', '#7fbc41', '#b8e186', '#e6f5d0', '#f7f7f7',
                  '#fde0ef', '#f1b6da', '#de77ae', '#c51b7d', '#8e0152'],
    'PRGn'     : ['#00441b', '#1b7837', '#5aae61', '#a6dba0', '#d9f0d3', '#f7f7f7',
                  '#e7d4e8', '#c2a5cf', '#9970ab', '#762a83', '#40004b'],
    'Spectral' : ['#5e4fa2', '#3288bd', '#66c2a5', '#abdda4', '#e6f598', '#ffffbf',
                  '#fee08b', '#fdae61', '#f46d43', '#d53e4f', '#9e0142'],
    # Viridis color maps (11 colors; from the R viridisLite package; also in matplotlib).
    # These are sequential, perceptually uniform color maps, so the middle color (log2
    # of 0) is not a neutral color. `cividis` is optimized for color vision deficiency.
    'viridis'   : ['#440154', '#482576', '#414487', '#35608d', '#2a788e', '#21908c',
                  '#22a884', '#43bf71', '#7ad151', '#bbdf27', '#fde725'],
    'magma'     : ['#000004', '#150e37', '#3b0f70', '#641a80', '#8c2981', '#b63679',
                  '#de4968', '#f76f5c', '#fe9f6d', '#fece91', '#fcfdbf'],
    'inferno'   : ['#000004', '#170c3a', '#420a68', '#6b186e', '#932667', '#bb3754',
                  '#dd513a', '#f3771a', '#fca50a', '#f6d645', '#fcffa4'],
    'plasma'    : ['#0d0887', '#42049e', '#6a00a8', '#900da4', '#b12a90', '#cc4678',
                  '#e16462', '#f1844b', '#fca636', '#fcce25', '#f0f921'],
    'cividis'   : ['#00204d', '#00326f', '#31446b', '#4e576c', '#666970', '#7c7b78',
                  '#958f78', '#b0a473', '#cbba69', '#e7d159', '#ffea46'],
    'rocket'    : ['#03051a', '#261433', '#4c1d4b', '#751f58', '#a11a5b', '#cb1b4f',
                  '#e83f3f', '#f2704d', '#f69c73', '#f7c5a5', '#faebdd'],
    'mako'      : ['#0b0405', '#26172a', '#382a54', '#414081', '#395d9c', '#357ba2',
                  '#3497a9', '#3db4ad', '#60ceac', '#a8e1bc', '#def5e5'],
    'turbo'     : ['#30123b', '#455bcd', '#3e9bfe', '#18d6cb', '#46f884', '#a2fc3c',
                  '#e1dd37', '#fea632', '#f05b12', '#c42503', '#7a0403'],
}
PALETTE = 'RedYellowBlue'

def hex_to_rgb(hex_color):
    '''Convert a hex color (e.g., #ff0000) to an RGB tuple in the [0, 1] range.'''
    hex_color = hex_color.lstrip('#')
    assert len(hex_color) == 6
    return tuple( int(hex_color[i:i+2], 16)/255.0 for i in (0, 2, 4) )

def set_palette(name=PALETTE, reverse=False):
    '''
    Get the RGB colors of a given palette, ordered from the lowest
    to the highest values (reversed if specified).
    '''
    assert name in PALETTES, f'Error: Palette {name} not available.'
    palette = [ hex_to_rgb(color) for color in PALETTES[name] ]
    assert len(palette) >= 3 and len(palette) % 2 == 1
    if reverse:
        palette = palette[::-1]
    return palette


# DEPRECATED: Not used for plotting since the adjusted values are now log2
# enrichments centered at 0. Kept for reference; see `diverging_color_gradient()`.
def scale_sigmoid_color_mean(mean, val):
    '''
    Plot the values using a Gompertz curve: y(t) = ae^(-be(^-ct))
      https://en.wikipedia.org/wiki/Gompertz_function
    The X-axis scales from 0 to 10, Y-axis from 0 to 1; we have shifted
    the curve to the right by subtracting 2 from val; we will shit it 
    more to line the sigmoid curve up with the mean value.
    '''
    val  = math.fabs(val)
    val  = val * 10
    mean = mean * 10 / 2
    a    = 1
    b    = 1
    c    = 0.5
    val  = a * math.exp(-1 * b * (math.exp(-1 * c * (val - 2 - mean))))
    return val

# DEPRECATED: Not used for plotting since the adjusted values are now log2
# enrichments centered at 0. Kept for reference; see `diverging_color_gradient()`.
def three_color_gradient(rgb1, rgb2, rgb3, mean, alpha, max_scale):
    (r1, g1, b1) = rgb1
    (r2, g2, b2) = rgb2
    (r3, g3, b3) = rgb3

    # Adjust mean and alpha so that max value is 1.0
    adj_mean = mean/max_scale
    adj_alpha = alpha/max_scale
    adj_alpha = scale_sigmoid_color_mean(adj_mean, adj_alpha)
    # scaled_alpha = float(alpha)
    if (adj_alpha < adj_mean):
        # scaled_alpha = float(alpha) / mean
        scaled_alpha = float(adj_alpha) / adj_mean
        r = ((1.0 - scaled_alpha) * r1) + (scaled_alpha * r2)
        g = ((1.0 - scaled_alpha) * g1) + (scaled_alpha * g2)
        b = ((1.0 - scaled_alpha) * b1) + (scaled_alpha * b2)
    else:
        # scaled_alpha = float(alpha - mean) / (1.0 - mean)
        scaled_alpha = float(adj_alpha - adj_mean) / (1.0 - adj_mean)
        r = (scaled_alpha * r3) + ((1.0 - scaled_alpha) * r2)
        g = (scaled_alpha * g3) + ((1.0 - scaled_alpha) * g2)
        b = (scaled_alpha * b3) + ((1.0 - scaled_alpha) * b2)
    return (r, g, b)

def diverging_color_gradient(palette, value, scale_min, scale_max):
    '''
    Map a log2 enrichment value to a color on a diverging scale centered
    at 0 (the genome-wide average). Negative values are scaled to the lower
    half of the palette based on scale_min, and positive values to the upper
    half based on scale_max, so each side can have a different range. Values
    are clamped to [scale_min, scale_max]. The palette is a list of RGB colors
    ordered from the lowest to the highest values, with the middle color at 0;
    colors are linearly interpolated between consecutive stops.
    '''
    assert scale_min < 0 < scale_max
    assert len(palette) >= 3 and len(palette) % 2 == 1
    # Scale to [-1, 1], and then to a position along the palette stops
    if value >= 0:
        scaled = min(1.0, value/scale_max)
    else:
        scaled = max(-1.0, value/math.fabs(scale_min))
    position = ((scaled + 1.0)/2.0) * (len(palette) - 1)
    i = min(int(position), len(palette) - 2)
    frac = position - i
    (r, g, b) = [ ((1.0 - frac) * low) + (frac * high)
                  for low, high in zip(palette[i], palette[i+1]) ]
    return (r, g, b)

# Set PyCairo environment
#
# Class to set the settings to the image output
class Image:
    def __init__(self, height=IMG_HEIGHT, width=IMG_WIDTH, font_size=FONT_SIZE, 
                 img_type='pdf', offset=25, edge=15):
        assert offset > edge
        # General Plot info
        self.height = height
        self.width  = width
        self.font   = font_size
        self.type   = img_type
        self.edge   = edge
        self.offset = offset
        self.max_y  = edge
        self.min_y  = height-edge
        self.min_x  = edge
        self.max_x  = width-edge
        # Position for the objects
        self.min_chr = offset
        self.max_chr = self.max_x
        self.min_tck = self.max_y
        self.max_tck = height-offset
        # Position for labels
        self.len_lab = height-edge
        self.chr_lab = offset-edge
    def fit_chrom_labels(self, context, labels, pad=5):
        '''
        Place the start of the chromosomes after the widest chromosome
        label, so that the labels are not cut off at the left edge.
        The labels are right-aligned to self.chr_lab.
        '''
        context.set_font_size(self.font)
        # Width of the label from the drawing point, including the bearing
        max_width = max([ context.text_extents(label)[0] + context.text_extents(label)[2]
                          for label in labels ])
        self.min_chr = max(self.offset, self.min_x + max_width + pad)
        self.chr_lab = self.min_chr - pad
    def scale_bp_to_pix(self, pos_bp, max_bp):
        scaled_x = ((pos_bp/max_bp)*(self.max_chr - self.min_chr)) + self.min_chr
        return scaled_x
    def cairo_context(self, plot_out_dir):
        if self.type == 'pdf':
            surface = cairo.PDFSurface(plot_out_dir, self.width, self.height)
            context = cairo.Context(surface)
            return surface, context
        elif self.type == 'svg':
            surface = cairo.SVGSurface(plot_out_dir, self.width, self.height)
            context = cairo.Context(surface)
            return surface, context
        else:
            sys.exit("The only supported formats are \'PDF\' and \'SVG\'.")


#
# Plot gridlines
#
def plot_gridlines(chromosomes, image, context, scale=SCALE, step=STEP):
    assert type(chromosomes) is dict
    assert isinstance(list(chromosomes.values())[0], Chromosome)
    assert isinstance(image, Image)
    # Reset font size
    context.set_font_size(image.font)
    # Plot the gridlines
    max_bp = max([ chromosomes[chrom].len for chrom in chromosomes ])
    assert max_bp > step
    grid = list(range(0,(max_bp+step),step))
    max_grd = max(grid)
    for bp in grid:
        # Add gridlines
        y1 = image.min_tck
        y2 = image.max_tck+(image.max_y/4)
        x = image.scale_bp_to_pix(bp, max_grd)
        context.set_dash([6.0, 3.0])
        context.set_line_cap(cairo.LINE_CAP_BUTT)
        context.move_to(x, y1)
        context.line_to(x, y2)
        ticks_col = ChromColors('ticks')
        context.set_source_rgb(ticks_col.r, ticks_col.g, ticks_col.b)
        context.set_line_width(0.75)
        context.stroke()
        # Add labels
        label = f'{int(bp//scale)}M'
        label_height = context.text_extents(label)[3]
        label_width  = context.text_extents(label)[2]
        txt_col = ChromColors('text')
        lab_x = x-(label_width/2)
        lab_y = image.len_lab+(label_height)
        context.move_to(lab_x, lab_y)
        context.set_source_rgb(txt_col.r, txt_col.g, txt_col.b)
        context.show_text(label)
    return max_grd

#
# Process the chromosomes
#
def process_chromosomes(chromosomes, chrom_order, wins_dict, image, 
                        context, max_grd, scale_min, scale_max, palette,
                        plot_type='proportion', scale=SCALE, step=STEP):
    assert type(chromosomes) is dict
    assert isinstance(list(chromosomes.values())[0], Chromosome)
    assert type(wins_dict) is dict
    assert isinstance(image, Image)
    assert len(chromosomes) == len(chrom_order)
    assert plot_type in ['proportion', 'count']

    # Plot the chromosomes and values
    chr_step = (image.max_tck-image.min_tck)/len(chromosomes)
    min_step = chr_step/4
    y = image.min_tck

    ## Loop over the chromosomes
    for chromosome in chrom_order:
        assert chromosome in chromosomes
        # Define the boundaries of the chromosome
        bp = chromosomes[chromosome].len
        x1 = image.min_chr
        x2 = image.scale_bp_to_pix(bp, max_grd)
        y1 = y+(1*min_step)
        y2 = y+(3*min_step)

        # Extract the windows for the current chromosome
        for window in wins_dict[chromosome]:
            assert isinstance(window, WindowStat)
            if window.mid > bp:
                continue
            x = image.scale_bp_to_pix(window.mid, max_grd)
            # Select the corresponding value type to plot
            value = window.proportion
            if plot_type == 'count':
                value = window.n_elements
            # Scale the colors based on the log2 enrichment
            (r, g, b) = diverging_color_gradient(palette, value, scale_min, scale_max)
            # Plot a line for the midpoint of a given window.
            # Not a polygon to prevent overlapping between windows.
            context.set_dash([])
            context.move_to(x, y1)
            context.line_to(x, y2)
            context.set_source_rgb(r, g, b)
            context.stroke()

        # Add the Chromosome len boxes
        context.set_dash([])
        context.move_to(x1, y1)
        context.line_to(x2, y1)
        context.line_to(x2, y2)
        context.line_to(x1, y2)
        context.close_path()
        context.set_line_width(1.0)
        col = ChromColors('border')
        context.set_source_rgb(col.r, col.g, col.b)
        # context.stroke_preserve()
        context.stroke()
        # col = ChromColors('fill')
        # context.set_source_rgb(col.r, col.g, col.b)
        # context.fill()

        # Add the labels
        label = str(chromosomes[chromosome].name)
        label_height = context.text_extents(label)[3]
        label_width = context.text_extents(label)[0] + context.text_extents(label)[2]
        # Right-align the labels next to the start of the chromosomes
        lab_x = image.chr_lab-label_width
        lab_y = (y+(2*min_step))+(label_height/2)
        txt_col = ChromColors('text')
        context.move_to(lab_x, lab_y)
        context.set_source_rgb(txt_col.r, txt_col.g, txt_col.b)
        context.show_text(label)
        y += chr_step

#
# Draw the Scale
#
def scale_side_ticks(limit, max_ticks=3):
    '''
    Set the intermediate tick marks for one side of the color scale, i.e.,
    between 0 and the given limit. Use the smallest 'nice' step that results
    in at most max_ticks ticks, and skip those too close to the limit.
    '''
    assert limit != 0
    sign = 1 if limit > 0 else -1
    limit = math.fabs(limit)
    step = limit
    for nice in [0.25, 0.5, 1, 2, 5, 10, 20, 50]:
        if limit/nice <= max_ticks:
            step = nice
            break
    ticks = list()
    tick = step
    # Skip ticks that are within 40% of a step from the limit, for space purposes
    while tick < limit - (0.4*step):
        ticks.append(sign*tick)
        tick += step
    return ticks

def draw_scale(image, context, scale_min, scale_max, palette):
    assert isinstance(image, Image)
    assert scale_min < 0 < scale_max
    # Boundaries
    x1 = image.max_x*0.985
    x2 = image.max_x*1.015
    y1 = image.max_tck*0.795
    y2 = image.max_tck*0.995
    key_h = y2-y1
    # Scale a log2 value to a Y position in the key. The value of 0 is at the
    # middle of the key, with the negative values scaled to the lower half
    # and the positive values to the upper half.
    def scale_val_to_y(val):
        if val >= 0:
            frac = 0.5 + (0.5*(val/scale_max))
        else:
            frac = 0.5 - (0.5*(val/scale_min))
        return y2-(key_h*frac)
    # Loop over the color space, from the bottom to the top of the key
    for frac in np.linspace(0, 1, 401):
        if frac >= 0.5:
            p = (frac - 0.5)*2*scale_max
        else:
            p = (0.5 - frac)*2*scale_min
        (r, g, b) = diverging_color_gradient(palette, p, scale_min, scale_max)
        yp = y2-(key_h*frac)
        context.set_dash([])
        context.move_to(x1, yp)
        context.line_to(x2, yp)
        context.set_source_rgb(r, g, b)
        context.stroke()
    # Outer box
    context.set_dash([])
    context.move_to(x1, y1)
    context.line_to(x2, y1)
    context.line_to(x2, y2)
    context.line_to(x1, y2)
    context.close_path()
    context.set_line_width(1.0)
    col = ChromColors('border')
    context.set_source_rgb(col.r, col.g, col.b)
    # context.stroke_preserve()
    context.stroke()
    col = ChromColors('fill')
    context.set_source_rgb(col.r, col.g, col.b)
    context.fill()

    #
    # Add labels
    #
    # Ticks at 0 (the genome-wide average) and the limits of the scale,
    # plus intermediate ticks on each side
    label_ticks = [0.0, scale_min, scale_max]
    for limit in [scale_min, scale_max]:
        label_ticks += scale_side_ticks(limit)
    # Decrease the font size for the labels
    context.set_font_size((image.font)*0.8) 
    # Plot the axis ticks
    # Format all the labels with the same number of decimal places: at least
    # one, or the most needed by any of the ticks (e.g., two for 0.25)
    decimals = max([1] + [ len(f'{round(tick, 3):g}'.partition('.')[2])
                           for tick in label_ticks ])
    for tick in label_ticks:
        lab = f'{tick:.{decimals}f}'
        label_height = context.text_extents(lab)[3]
        # Right-align using the advance width, so that the digits line up
        # regardless of the bearing and ink width of each glyph
        label_width = context.text_extents(lab)[4]
        lab_x = (x1*0.995)-label_width
        lab_y = scale_val_to_y(tick)+(label_height/2)
        txt_col = ChromColors('text')
        context.move_to(lab_x, lab_y)
        context.set_source_rgb(txt_col.r, txt_col.g, txt_col.b)
        context.show_text(lab)

    # Add the title of the scale, centered above the color key
    lab = 'log2'
    (lab_xb, lab_yb, label_width, label_height, _, _) = context.text_extents(lab)
    lab_x = x1+((x2-x1)/2)-(lab_xb+(label_width/2))
    # Leave space between the key and the bottom of the text (e.g., the descender of 'g')
    lab_y = y1-(label_height+lab_yb)-(image.font*0.3)
    txt_col = ChromColors('text')
    context.move_to(lab_x, lab_y)
    context.set_source_rgb(txt_col.r, txt_col.g, txt_col.b)
    context.show_text(lab)

    # Reset font size
    context.set_font_size(image.font)

# Add title to the figure
def draw_title(image, context, title):
    assert isinstance(image, Image)
    x = image.min_chr
    y = image.max_y
    # Reset font size
    context.set_font_size(image.font*1.25)
    # Adjust height
    title_height = context.text_extents(title)[3]
    y = y-(title_height/2)
    txt_col = ChromColors('text')
    context.move_to(x,y)
    context.set_source_rgb(txt_col.r, txt_col.g, txt_col.b)
    context.show_text(title)


def get_window_values(win_val_dict, value_type='proportion'):
    '''
    Iterate over the windows dictionary and get the distribution of
    genome-wide log2 enrichment values.
    '''
    assert value_type in ['proportion', 'count']
    values = list()
    for chr in win_val_dict:
        for window in win_val_dict[chr]:
            assert isinstance(window, WindowStat)
            if value_type == 'proportion':
                values.append(window.proportion)
            else:
                values.append(window.n_elements)
    return np.array(values)

def auto_scale_limit(values, quantile=SCALE_QUANTILE, round_to=SCALE_ROUND, side='both'):
    '''
    Set a limit of the color scale from the data, rounded away from 0 to the
    nearest `round_to` value (with a minimum magnitude of `round_to`):
      both:  the given percentile of the absolute log2 values (symmetric scale).
      upper: the given percentile of the log2 values.
      lower: the (100 - quantile) percentile of the log2 values (a negative limit).
    '''
    assert 0 < quantile <= 100
    assert round_to > 0
    assert side in ['both', 'upper', 'lower']
    if side == 'both':
        limit = np.percentile(np.abs(values), quantile)
    elif side == 'upper':
        limit = np.percentile(values, quantile)
    else:
        limit = -1*np.percentile(values, 100-quantile)
    limit = max(round_to, math.ceil(limit/round_to)*round_to)
    if side == 'lower':
        limit = -1*limit
    return limit

def ordinal(number):
    '''Format a number as an ordinal, e.g., 1st, 2nd, 99th, 99.5th.'''
    text = f'{number:g}'
    if not float(number).is_integer() or 10 <= int(number) % 100 <= 20:
        return f'{text}th'
    return text + {1: 'st', 2: 'nd', 3: 'rd'}.get(int(number) % 10, 'th')

def set_scale_limits(values, min_log2=None, max_log2=MAX_LOG2, quantile=SCALE_QUANTILE):
    '''
    Set the lower and upper limits of the color scale. Each limit is either
    a number or 'auto' (set from the data). If min_log2 is not set, the scale
    is symmetric around 0, i.e., [-max_log2, max_log2].
    Returns the two limits and a description of how they were set.
    '''
    if min_log2 is None:
        # Symmetric scale
        if max_log2 == 'auto':
            limit = auto_scale_limit(values, quantile, side='both')
            source = f'Auto, symmetric; {ordinal(quantile)} percentile of |log2| = {np.percentile(np.abs(values), quantile):,.4g}, rounded up'
        else:
            limit = max_log2
            source = 'Fixed, symmetric'
        return -1*limit, limit, source
    # Asymmetric scale, each side set independently
    sources = list()
    if min_log2 == 'auto':
        scale_min = auto_scale_limit(values, quantile, side='lower')
        sources.append(f'min: auto; {ordinal(100-quantile)} percentile = {np.percentile(values, 100-quantile):,.4g}, rounded down')
    else:
        scale_min = min_log2
        sources.append('min: fixed')
    if max_log2 == 'auto':
        scale_max = auto_scale_limit(values, quantile, side='upper')
        sources.append(f'max: auto; {ordinal(quantile)} percentile = {np.percentile(values, quantile):,.4g}, rounded up')
    else:
        scale_max = max_log2
        sources.append('max: fixed')
    return scale_min, scale_max, f'Asymmetric; {"; ".join(sources)}'

def report_value_distribution(values, scale_min, scale_max, source):
    '''
    Report the distribution of the log2 enrichment values, including how
    many fall outside the limits of the color scale.
    '''
    n_low = np.sum(values < scale_min)
    n_high = np.sum(values > scale_max)
    print(f'''    Log2 enrichment across {len(values):,} windows:
        Min: {np.min(values):,.4g}; Median: {np.median(values):,.4g}; Max: {np.max(values):,.4g}
        Color scale limits: {scale_min:g} to {scale_max:g} ({source})
        Clamped to the color scale: {n_low:,} below; {n_high:,} above''',
          flush=True)


# Draw a figure
def draw_genome_stats(outf, chromosomes, chrom_order, win_val_dict, 
                      name, plot_type = 'proportion',
                      height=IMG_HEIGHT, width=IMG_WIDTH, 
                      scale=SCALE, step=STEP, img_type='pdf',
                      min_log2=None, max_log2=MAX_LOG2, quantile=SCALE_QUANTILE,
                      palette=None):
    if palette is None:
        palette = set_palette(PALETTE)
    print(f'\nMaking plot ({name}):\n    {outf}', flush=True)
    # Set an image object global variable
    image = Image(height=height, width=width, img_type=img_type)
    surface, context = image.cairo_context(outf)
    # Adjust the start of the chromosomes to the width of their labels
    image.fit_chrom_labels(context, [ str(chromosomes[chrom].name) for chrom in chrom_order ])
    # Get the distribution of values along the genome, and set the limits
    # of the color scale, either fixed or from the data
    values = get_window_values(win_val_dict, plot_type)
    scale_min, scale_max, source = set_scale_limits(values, min_log2, max_log2, quantile)
    report_value_distribution(values, scale_min, scale_max, source)
    # Plot gridlines
    max_grd = plot_gridlines(chromosomes, image, context, scale, step)
    # Process the chromosomes
    process_chromosomes(chromosomes, chrom_order, win_val_dict, 
                        image, context, max_grd, scale_min, scale_max, palette,
                        plot_type, scale, step)
    # Plot the scale
    draw_scale(image, context, scale_min, scale_max, palette)
    # Add title
    draw_title(image, context, name)


def date():
    '''Print the current date in YYYY-MM-DD format.'''
    return datetime.datetime.now().strftime("%Y-%m-%d")

def time():
    '''Print the current time in HH:MM:SS format.'''
    return datetime.datetime.now().strftime("%H:%M:%S")


def main():
    print(f'{PROG} started on {date()} {time()}.')
    args = parse_args()
    print(f'    Min Chrom Length: {int(args.min_len):,} bp')

    # Load chromosome information
    chromosomes, chrom_order = process_chromosome_info(args.fai, args.chroms, args.min_len)

    # Load the target genetic elements
    windows = load_window_stats_file(args.in_table, chromosomes)

    # Set the color palette
    palette = set_palette(args.palette, args.reverse_palette)
    print(f'\nUsing color palette: {args.palette}{" (reversed)" if args.reverse_palette else ""}', flush=True)

    # Plot the genome stats
    title = args.basename if args.title is None else args.title

    # 1. For the number of elements
    outf = f'{args.out_dir}/{args.basename}.num_elements.{args.img_format}'
    name = f'{title} : Number of elements per window (log2 enrichment)'
    draw_genome_stats(outf, chromosomes, chrom_order, windows, name, 
                      plot_type='count', height=args.img_height, width=args.img_width,
                      scale=args.scale, step=args.step, img_type=args.img_format,
                      min_log2=args.min_log2, max_log2=args.max_log2,
                      quantile=args.scale_quantile,
                      palette=palette)

    # 2. For the proportion of sites
    outf = f'{args.out_dir}/{args.basename}.site_proportions.{args.img_format}'
    name = f'{title} : Proportion of sites per window (log2 enrichment)'
    draw_genome_stats(outf, chromosomes, chrom_order, windows, name, 
                      plot_type='proportion', height=args.img_height, width=args.img_width,
                      scale=args.scale, step=args.step, img_type=args.img_format,
                      min_log2=args.min_log2, max_log2=args.max_log2,
                      quantile=args.scale_quantile,
                      palette=palette)


    print(f'\n{PROG} finished on {date()} {time()}.')

# Run Code
if __name__ == '__main__':
    main()
